### ISSUE TITLE
Request failed with status code 401 using a 'Job Admin' service token

### ISSUE THREAD

**Issue by maxpowis-bp** [fal-ai/dbt-cloud-action#27]
Hi, 
It is my first time trying to use this github-action. So far, I have successfully used the following step specification.

```yaml
      - id: dbt_cloud_run
        name: Run dbt job on target environment
        run: |
          RESPONSE=$(curl -v -H "Authorization:Token ${{ secrets.DBT_CLOUD_API_TOKEN }}" -H "Content-Type:application/json" \
            -d '{"cause":"Triggered by Github Action"}' \
            https://emea.dbt.com/api/v2/accounts/${{ vars.DBT_CLOUD_ACCOUNT_ID }}/jobs/${{ vars.DBT_CLOUD_JOB_ID }}/run/)
          STATUSCODE=$(echo "$RESPONSE" | jq '.status.code')
          echo "$RESPONSE" | jq '.status.user_message'
          if [[ $STATUSCODE != 200 ]]; then
            echo "$RESPONSE"
            bash -c "exit 1"
          fi
```

However, I'd be interested in replacing it with this github action as a mean to get the actual job outputs status. So I have tried amending my step as follows:

```yaml
      - id: dbt_cloud_run
        name: Run dbt job on target environment
        uses: fal-ai/dbt-cloud-action@v4.3
        with:
          dbt_cloud_token: ${{ secrets.DBT_CLOUD_API_TOKEN }}
          dbt_cloud_account_id: ${{ vars.DBT_CLOUD_ACCOUNT_ID }}
          dbt_cloud_job_id: ${{ vars.DBT_CLOUD_JOB_ID }}
          failure_on_error: true
```

Unfortunately, it fails with the following debug log outputs that seem to indicate my token is not properly configured. 

```text
##[debug]Loading env
Run fal-ai/dbt-cloud-action@v4.3
##[debug]Run job body:
##[debug]{
##[debug]  "cause": "Triggered by a GitHub Action"
##[debug]}
Error: There has been a problem with running your dbt cloud job:
Error: Request failed with status code 401
##[debug]Error: Request failed with status code 401
##[debug]    at createError (/home/runner/work/_actions/fal-ai/dbt-cloud-action/v4.3/node_modules/axios/lib/core/createError.js:16:15)
##[debug]    at settle (/home/runner/work/_actions/fal-ai/dbt-cloud-action/v4.3/node_modules/axios/lib/core/settle.js:17:12)
##[debug]    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/fal-ai/dbt-cloud-action/v4.3/node_modules/axios/lib/adapters/http.js:269:11)
##[debug]    at IncomingMessage.emit (node:events:525:35)
##[debug]    at endReadableNT (node:internal/streams/readable:13[58](***MASKED***):12)
##[debug]    at processTicksAndRejections (node:internal/process/task_queues:83:21)
##[debug]Node Action run completed with exit code 1
##[debug]Finishing: Run dbt job on target environment
```

In my previous implementation, I have used a service token with 'Job Admin' scope on my project. I can see in dbt cloud that my token (a new one with the exact same config) is actually never accessed. Do I need to consider another - more extensive - permission?

Thanks in advance for your support.

**Comment by maxpowis-bp** [comment]
Look like to is due to the fact my dbt endpoint is on the domain emea.dbt.com while the https://github.com/fal-ai/dbt-cloud-action/blob/08fd3588f25a91faa328c858664f11daeee5f9f2/index.js#L26C37-L26C37 hardcodes the domain to cloud.getdbt.com

**Comment by maxpowis** [comment]
As per https://docs.getdbt.com/dbt-cloud/api-v2#/ API base url's can be:
- Production (US):https://cloud.getdbt.com
- Production (Europe):https://emea.dbt.com
- Production (AU):https://au.dbt.com

**Comment by maxpowis** [comment]
Created PR https://github.com/fal-ai/dbt-cloud-action/pull/28
